nutrihuapp/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^$', views.index_view, name="index"),
	url(r'^signup/$', views.signup_view, name="signup"),
	url(r'^dashboard/$', views.dashboard_view, name="dashboard"),
	url(r'^dashboard/analyze/$', views.analyze_view, name="analyze"),
	url(r'^dashboard/nearme/$', views.nearme_view, name="nearme"),
	url(r'^dashboard/recommendedfood/$', views.recfood_view, name="recfood"),
	url(r'^dashboard/mybody/$', views.mybody_view, name="mybody"),
	url(r'^dashboard/donate/$', views.donate_view, name="donate"),
	url(r'^update/$', views.update_view, name="update"),
	url(
		r'^login/$',
		'django.contrib.auth.views.login',
		name='login',
		kwargs={ 'template_name' : 'HUnutrition/login.html'}
		),
	url(
		r'^accounts/logout/$',
		'django.contrib.auth.views.logout',
		name="logout",
		kwargs={'next_page' : '/'}
		),
	url(r'^htmldevelopment$', views.html_development_view, name="htmldevelopment"),
]

summer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('nutrihuapp.urls', namespace="HUnutrition")),
    url(r'^admin/', include(admin.site.urls)),
]

nutrihuapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class Person(models.Model):	
	def __unicode__(self):
		return self.user.username
	
	user = models.OneToOneField(settings.AUTH_USER_MODEL)

	signed_up_time = models.DateField(auto_now_add=True)
	current_weight = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	current_height = models.PositiveSmallIntegerField(default=0)
	current_bmi = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	current_bmr = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	current_tdee = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	current_met = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
	current_age = models.PositiveSmallIntegerField(default=25)
	workout = models.CharField(default='C', max_length=2)
	gender = models.CharField(default='m', max_length=2)
	diseases = models.TextField(default='none')
	aim = models.CharField(default='C', max_length=2)
	color = models.CharField(default='green', max_length=6)

nutrihuapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
import json
import urllib2
from django.http import HttpResponse, HttpResponseRedirect
from .models import Person
from django.contrib.auth import authenticate, login
from samman import UsernameValidated, PasswordValidated, EmailValidated, bmi, bmr, tdee, met, color, CreateCache
from twitter import get_all_words, not_symbol, get_all_nouns, get_highest_valued_keys, main, get_youtube_links

google_apiKey = 'AIzaSyBkOwZ54lszh7W6hm_jKx_ehuTigL1lIN8'
google_client_id = '364020523774-gsvrr7ov6mtphn8iav2ort26n3js36l0.apps.googleusercontent.com'
nutritionix_api = 'https://api.nutritionix.com/v1_1/search/'
nutritionix_api_fields = 'fields=item_name,brand_name,item_id,nf_calories'
nutritionix_appKey = 'd150be1ac1688616495f3dd78d40483b'
nutritionix_appId= '76284f94'
cache_dic = {}
consumer_key = 'hrOpsDPRDtmKFA5ZvtSm4KpJy'
consumer_secret = 'aXaaRF5IXtmZeWs2sEP64Uz7QExBn32YTeajftfGSuKDmZ0KCy'
access_token = '2750763448-6B1i89sT0ullMjmMk7cPOhaInZPeLVVwlFk9SvN'
access_token_secret = 'JKpprBcIWFbtrO7TxzQpnZ97ZRHdi0gEiQ7efYbJb6ETO'


def signup_view(request, username="", email="", age="", weight="", height="", gender="", workout="", diseases="", aim="", error=""):
	if request.POST:
		username = request.POST['username']
		password = request.POST['password']
		verify_password = request.POST['verify_password']
		email = request.POST['email']
		age = request.POST['age']
		weight = request.POST['weight']
		height = request.POST['height']
		gender = request.POST['gender']
		workout = request.POST.get('exercise', 'A')
		diseases = request.POST.getlist('diseases')
		aim = request.POST['aim']
		try:
			wrong = []
			err = ""
			if UsernameValidated(username, wrong) and PasswordValidated(password, verify_password, wrong) and EmailValidated(email, wrong):
				BMI = bmi(weight, height)
				BMR = bmr(weight, height, age, gender)
				TDEE = tdee(workout, BMR)
				MET = met(BMR, workout)
				COLOR = color(BMR, TDEE, MET, diseases, aim)
				user = User.objects.create_user(username=username, email=email, password=password)
				user.save()
				person = Person(user=user, workout=workout, gender=gender, diseases=diseases, aim=aim, current_weight=weight, current_height=height,
								current_bmi=BMI, current_bmr=BMR, current_tdee=TDEE, current_met=MET, color=COLOR)
				person.save()
				user.backend = "django.contrib.auth.backends.ModelBackend"
				login(request, user)
				return redirect('HUnutrition:dashboard')
			else:
				for wrongs in wrong:
					err += wrongs
				error="%(wrong)s is not correct" % {"wrong" : err}
		except ValueError:
				error="The user " + username + " already exists."
	return render(request, 'HUnutrition/signup.html', {'title' : 'HU-Nutn : Sign Up', 'username' : username, 'error' : error, 'email' : email, 'age' : age, 'weight' : weight, 'height' : height})


def index_view(request):
	if request.user and request.user.is_authenticated():
		return redirect('HUnutrition:dashboard')
	return render(request, 'HUnutrition/index.html', {'title' : 'HU-Nutn'})


@login_required
def dashboard_view(request):
	CreateCache(cache_dic, request.user)
	print cache_dic
	return render(request, 'HUnutrition/dashboard.html', {'title' : 'HU-Nutn', 'cached_memory' : cache_dic })


@login_required
def analyze_view(request):
	print 
	print "analyze: ", cache_dic
	print 
	if request.GET:
		print 
		print "received users queries"
		print 
		food = request.GET['food']
		restaurant = request.GET['restaurant']
		if food and restaurant:
			items = []
			data = nutritionix_api + food + '?' + nutritionix_api_fields + '&' + 'appKey=' + nutritionix_appKey + '&' + 'appId=' + nutritionix_appId
			page = urllib2.urlopen(data)
			page_read = page.read()
			page = json.loads(page_read)
			results = page['hits']
			for hits in results:
				if (hits['fields']['brand_name']).lower() in restaurant.lower() or restaurant.lower() in (hits['fields']['brand_name']).lower():
					items.append(hits)
			return render(request, "HUnutrition/search_result.html", {'title' : 'HU-Nutn : result', 'food' : food, 'restaurant' : restaurant,'results' : items, 'cached_memory' : cache_dic})
		elif food or restaurant:
			query = food + restaurant
			data = nutritionix_api + query + '?' + nutritionix_api_fields + '&' + 'appKey=' + nutritionix_appKey + '&' + 'appId=' + nutritionix_appId
			page = urllib2.urlopen(data)
			page_read = page.read()
			page = json.loads(page_read)
			results = page['hits']
			return render(request, "HUnutrition/search_result.html", {'title' : 'HU-Nutn : result', 'food' : food, 'restaurant' : restaurant,'results' : results, 'cached_memory' : cache_dic})
		return render(request, "HUnutrition/search_result.html", {'title' : 'HU-Nutn : result'})
	return render(request, 'HUnutrition/analyze.html', {'title' : 'HU-Nutn : Analyze Food', 'cached_memory' : cache_dic})


@login_required
def nearme_view(request):
	data_place = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
	"""data_location = 'https://www.googleapis.com/geolocation/v1/geolocate?key='
	page = urllib2.urlopen(data_location+google_apiKey)
	location = json.loads(page.read())
	current_latitude = location['location']['lat']
	current_longitude = location['location']['lng']
	"""
	#i have hardcoded the location of DC in the following latitude and longitude, however, longitude and latitude needs to be received from above
	page = urllib2.urlopen(data_place + 'location=38.8977,-77.0366' + '&radius=500' + '&types=restaurant|bar|food' + '&key=' + google_apiKey)
	page_read = page.read()
	page = json.loads(page_read)
	results = page['results']
	return render(request, 'HUnutrition/nearme.html', {'title' : 'HU-Nutn : Near Me', 'results' : results, 'cached_memory' : cache_dic})


@login_required
def recfood_view(request, username=""):
	if (cache_dic['color'] == 'green'):
		max_calorie = 2000
	elif (cache_dic['color'] == 'yellow'):
		max_calorie = 750
	elif (cache_dic['color'] == 'red'):
		max_calorie = 350
	data = json.dumps({"appId":nutritionix_appId,
						"appKey":nutritionix_appKey,
						"query" : "*",
						"fields":["item_name","brand_name","upc","nf_calories"],
						"filters" :{ "nf_calories" : {"from":0,"to":max_calorie}}})
	req = urllib2.Request(nutritionix_api, data, {'Content-Type': 'application/json'})
	p = urllib2.urlopen(req)
	response = p.read()
	p.close()
	page = json.loads(response)
	results = page['hits']
	return render(request, 'HUnutrition/rec_food.html', {'title' : 'HU-Nutn : Recommended Food', 'results' : results, 'cached_memory' : cache_dic})


@login_required
def mybody_view(request):
	print cache_dic
	return render(request,'HUnutrition/mybody.html', {'title' : 'HU-Nutn : My Body', 'cached_memory' : cache_dic})


@login_required
def donate_view(request, username=""):
	return render(request, 'HUnutrition/donate.html', {'title' : 'HU-Nutn : Donate', 'cached_memory' : cache_dic})


@login_required
def update_view(request):
	new_age = request.POST['age']
	new_weight = request.POST['weight']
	new_height = request.POST['height']
	new_gender = request.POST['gender']
	new_workout = request.POST.get('exercise', 'A')
	new_diseases = request.POST.getlist('diseases')
	new_aim = request.POST['aim']
	new_BMI = bmi(new_weight, new_height)
	new_BMR = bmr(new_weight, new_height, new_age, new_gender)
	new_TDEE = tdee(new_workout, new_BMR)
	new_MET = met(new_BMR, new_workout)
	new_COLOR = color(new_BMR, new_TDEE, new_MET, new_diseases, new_aim)
	u = User.objects.get(username=request.user.username)
	u.person.current_weight = new_weight
	u.person.current_age = new_age
	u.person.current_height = new_height
	u.person.gender = new_gender
	u.person.workout = new_workout
	u.person.diseases = new_diseases
	u.person.aim = new_aim
	u.person.current_bmi = new_BMI
	u.person.current_bmr = new_BMR
	u.person.current_tdee = new_TDEE
	u.person.current_met = new_MET
	u.person.color = new_COLOR
	u.person.save()
	CreateCache(cache_dic, u)
	return redirect('HUnutrition:mybody')

@login_required
def html_development_view(request):
	return render(request, 'HUnutrition/html_development_page.html', {'title' : 'HU-Nutn : html development', 'cached_memory' : cache_dic})

nutrihuapp/templates/HUnutrition/analyze.html
{% extends 'HUnutrition/base-dashboard.html' %}

{% block dashboard-content %}

<style type="text/css">
	#analyze{
		background-color: rgb(204, 204, 255);
	}
</style>

<div class="row beside-side-nav">
	<div class="card-panel">
		<h5><p class="teal-text text-darken-3">Search Below</p></h5>
	</div>

	<div class="card-panel">
		<form method="get" action="{% url 'HUnutrition:analyze' %}">
			<div class="row">
				<div class="input-field col l5 offset-l3 m6 offset-m3 s12">
					<i class="mdi-maps-local-pizza prefix"></i>
					<input class="validate" id="food" name="food" type="text">
					<label for="food">Name of the Food</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col l5 offset-l3 m6 offset-m3 s12">
					<i class="mdi-maps-local-restaurant prefix"></i>
					<input type="text" id="brand" name="restaurant" class="validate">
					<label for="brand">Restaurant</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col l5 offset-l7 m6 offset-m6 s6 offset-s6">
					<button class="btn waves-effect waves-light" type="submit">Search
					<i class="mdi-content-send right"></i>
					</button>
				</div>
			</div>
		</form>
	</div>
</div>

{% endblock %}

nutrihuapp/templates/HUnutrition/base-dashboard.html
{% load staticfiles %}
<!doctype HTML>
<html lang="en">
<head>
    <!-- for proper rendering and touch zooming in mobiles-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

	<title>
		{{ title }}
	</title>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->

    <!-- import materialize -->
    <link rel="stylesheet" href="{% static 'HUnutrition/css/materialize.min.css' %}">

    <!-- self made stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'HUnutrition/css/style.css' %}"/>

     <!-- scripts -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'HUnutrition/js/materialize.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function(){
      $(".button-collapse").sideNav();
    });
      $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });
    </script>

</head>

<body>
	<header>
		<ul id="nav-mobile" class="side-nav fixed blue-grey">
			<li class="bold"><h5>Logo Goes Here</h5></li>
			<li class="bold" id="analyze"><a href="{% url 'HUnutrition:analyze' %}" class="waves-effect waves-teal">Analayze Your Food</a></li>
			<li class="bold" id="nearme"><a href="{% url 'HUnutrition:nearme' %}" class="waves-effect waves-teal">Restaurants Near Me</a></li>
			<li class="bold" id="rec_food"><a href="{% url 'HUnutrition:recfood' %}" class="waves-effect waves-teal">Recommended Food</a></li>
			<li  style="padding : 1.5em; padding-left : 0em" id="mybody">
				<ul class="collapsible collapsible-accordion">
					<li class="bold"><a href="#" class="waves-effect waves-teal collapsible-header">My Body Information</a>
						<div class="collapsible-body">
							<ul class="grey lighten-2">
								<li><a href="{% url 'HUnutrition:mybody' %}" class="waves-effect waves-teal">My Body</a></li>
								<li><a href="#" onclick="Materialize.toast('You are at Washington, DC', 12000)">Where Am I</a></li>
							</ul>
						</div>
					</li>
				</ul>
			</li>
			<li class="bold" id="donate"><a href="{% url 'HUnutrition:donate' %}" class="waves-effect waves-teal">Donate - help us help you</a></li>
		</ul>
	</header>
	<main>
		<div class="row">
			<div>
			    <div class="navbar-fixed navbar-holder-samman">
				    <nav>
				        <div class="nav-wrapper navbar-content-samman teal lighten-2">
					        <div class="col l10 offset-l2">
					        	<a href="{% url 'HUnutrition:dashboard' %}" class="brand-logo" style="padding-left:3em;">HUnutrition</a>
					        	<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
					        	<ul class="right hide-on-med-and-down">
					    			<li><a href="{% url 'HUnutrition:mybody' %}">{{cached_memory.username}}</a></li>
					    			<li><a href="{% url 'HUnutrition:logout' %}">Sign Out</a></li>
					  			</ul>
					  			<ul class="side-nav" id="mobile-demo">
					  				<li class="bold red-text"><h5>Logo Goes Here</h5></li>
					    			<li><a href="{% url 'HUnutrition:mybody' %}">{{cached_memory.username}}</a></li>
									<li class="bold"><a href="{% url 'HUnutrition:analyze' %}" class="waves-effect waves-teal">Analayze Your Food</a></li>
									<li class="bold"><a href="{% url 'HUnutrition:nearme' %}" class="waves-effect waves-teal">Restaurants Near Me</a></li>
									<li class="bold"><a href="{% url 'HUnutrition:recfood' %}" class="waves-effect waves-teal">Recommended Food</a></li>
									<li style="padding : 1em; padding-left : 0em">
										<ul class="collapsible collapsible-accordion">
											<li class="bold"><a href="#" class="waves-effect waves-teal collapsible-header">My Body Information</a>
												<div class="collapsible-body">
													<ul class="grey lighten-2">
														<li><a href="{% url 'HUnutrition:mybody' %}" class="waves-effect waves-teal">My Body</a></li>
														<li><a href="#" onclick="Materialize.toast('You are at Washington, DC', 12000)">Where Am I</a></li>
													</ul>
												</div>
											</li>
										</ul>
									</li>	
									<li class="bold"><a href="{% url 'HUnutrition:donate' %}" class="waves-effect waves-teal">Donate - help us help you</a></li>
					    			<li><a href="{% url 'HUnutrition:logout' %}">Sign Out</a></li>
					  			</ul>
					        </div>
				        </div>
				    </nav>
			    </div>
			</div>
		</div>
		<div class="row">
			<div class="col l10 offset-l2 m9 offset-m3 s12">
				{% block dashboard-content %}

				{% endblock %}
			</div>
		</div>
	</main>
	<footer class="page-footer" style="padding-left: 2em;">
		<div class="row">
			<div class="col l10 offset-l1 m10 offset-m1 s10 offset-s1">
				<div class="container">
					<div class="row">
						<div class="col l6 s12">
							<h5 class="white-text">Join The Discussion</h5>
							<p class="grey-text text-lighten-4">We have a Gitter chat room set up where you can talk directly with us. Come in and discuss new features, future goals, general problems or questions, or anything else you can think of.</p>
						</div>
						<div class="col l4 offset-l2 s12">
							<h5 class="white-text">Contact US</h5>
							<ul>
								<li><a class="grey-text text-lighten-3" href="https://github.com/">Github</a></li>
								<li><a class="grey-text text-lighten-3" href="https://facebook.com">Facebook</a></li>
								<li><a class="grey-text text-lighten-3" href="https://gmail.com">Gmail</a></li>
								<li><a class="grey-text text-lighten-3" href="https://htpchat.com">Hipchat</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container">
						© 2014 Copyright Text
						<a class="grey-text text-lighten-4 right" href="#!">Samman Bikram Thapa</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>

nutrihuapp/templates/HUnutrition/base.html
{% load staticfiles %}
<!doctype HTML>
<html lang="en">
<head>
    <!-- for proper rendering and touch zooming in mobiles-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

  <title>
    {{ title }}
  </title>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->

    <!-- import materialize -->
    <link rel="stylesheet" href="{% static 'HUnutrition/css/materialize.min.css' %}">

    <!-- self made stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'HUnutrition/css/style.css' %}"/>
</head>
<body>

<!--fixed navbar at the top of the page -->
    <div class="navbar-fixed navbar-holder-samman">
        <nav>
            <div class="nav-wrapper navbar-content-samman teal lighten-2">
            {% if True %}
              <a href="{% url 'HUnutrition:login' %}" class="brand-logo">Videofy</a>
            {% else %}
              <a href="{% url 'HUnutrition:dashboard' %}" class="brand-logo">Videofy</a>
            {% endif %}
              <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
              <ul class="right hide-on-med-and-down">
        <li><a href="#"></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#"></a></li>
      </ul>
            </div>
        </nav>
    </div>

    <main>
    {% block content %}

    {% endblock %}
    </main>
    
    <div class="divider"></div>

    <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Join The Discussion</h5>
                <p class="grey-text text-lighten-4">We have a Gitter chat room set up where you can talk directly with us. Come in and discuss new features, future goals, general problems or questions, or anything else you can think of.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Contact Us</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="https://github.com/">Github</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://facebook.com">Facebook</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://gmail.com">Gmail</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://htpchat.com">Hipchat</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">Samman Bikram Thapa</a>
            </div>
          </div>
        </footer>

 <!-- scripts -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'HUnutrition/js/materialize.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function(){
      $(".button-collapse").sideNav();
    })
    </script>
</body>
</html>

nutrihuapp/templates/HUnutrition/dashboard.html
{% extends 'HUnutrition/base-dashboard.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block dashboard-content %}

<div class="row beside-side-nav">
	<div class="card-panel">
		How've you been today? {{user}}
	</div>
	<div class="card-panel">
		<p>Use the side bar to the left to look at various features of the app. This app uses information provided from the nutrionix.com web app to get data about food, and uses the data you provided to analyze what food is good for you to eat.
		</p>
	</div>
</div>




{% endblock %}

nutrihuapp/templates/HUnutrition/donate.html
{% extends 'HUnutrition/base-dashboard.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block dashboard-content %}

<style type="text/css">
	#donate{
		background-color: rgb(204, 204, 255);
	}
</style>

<div class="row beside-side-nav">
	<div class="card-panel">
		<h3>Donate</h3>
	</div>

	<div class="card-panel">
		<p> Help us grow by donating for our cause at this site</p>
	</div>
</div>

{% endblock %}

nutrihuapp/templates/HUnutrition/html_development_page.html
{% extends 'HUnutrition/base.html' %}

{% block content %}
<nav>
  <ul class="right hide-on-med-and-down">
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
  <ul id="slide-out" class="side-nav">
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
</nav>
        
        <script type="text/javascript">
  // Initialize collapse button
  $(".button-collapse").sideNav();
  // Initialize collapsible (uncomment the line below if you use the dropdown variation)
  //$('.collapsible').collapsible();
  </script>

  {% endblock %}

nutrihuapp/templates/HUnutrition/index.html
{% extends "HUnutrition/base.html" %}

{% block content %}


<div class="container below-navbar">
	<div class="card-panel">
		<h2>Welcome to Videofy</h2>
		<div class="row card-panel white">
			<br>
			<p> If you don't know us yet, sign up. Sign up with us and enjoy life long video subscription that we get to you using our smart algorithms to suit your taste.
			</p>
		</div>
	</div>
	<div class=" row card-panel white">
		<a class="btn waves-effect waves-light col s12 m12 l12" href="{% url 'HUnutrition:signup' %}">Sign Up with Twitter</a>
		<br>
		<br>
	</div>
	OR
	<div class="row card-panel white">
		<br>
		<br>
		<a class="btn waves-effect waves-light col s12 m12 l12" href="{% url 'HUnutrition:login' %}">Login with Twitter</a>
	</div>
</div>

{% endblock %}

nutrihuapp/templates/HUnutrition/login.html
{% extends "HUnutrition/base.html" %}

{% block content %}

<div class="container below-navbar">
	<div class="row ">
		<div class="col l4 offset-l4 m4 offset-m4 s12">
		<form method="post" action="{% url 'HUnutrition:login' %}">
		{% csrf_token %}
			<fieldset  class="grey darken-1">
				<legend></legend>
				<div class="row">
					<div class="col l10 offset-l1">
						<div class="input-field">
							<input placeholder="  Username" id="username" type="text" class="validate" name="username">
							<label for="username"></label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col l10 offset-l1">
						<div class="input-field">
							<input placeholder="  Password" id="password" type="password" class="validate" name="password">
							<label for="password"></label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col l8 offset-l4 m8 offset-m4 s12">
						<button class="btn waves-effect waves-light" type="submit">Login<i class="mdi-content-send right"></i>
						</button>
					</div>
				</div>
				<input type="hidden" name="next" value="{% url 'HUnutrition:dashboard' %}"/>
				<div class="row">
					<div class="divider"></div>
					<div class="section">
						<div class="col l10 offset-l1 m10 offset-m1 s12 ">
							<a class="grey-text text-darken-3" href="{% url 'HUnutrition:login' %}"><u>Forgot Username or Password</u></a>
							<br>
							<a class="col l5 offset-l4 m4 offset-m4 s12 grey-text text-darken-3" href = "{% url 'HUnutrition:signup' %}"><u>Sign Up</u> </a>
							<br>
							<div class="red-text">
								<h5>{{ error }}</h5>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
</div>

{% endblock %}

nutrihuapp/templates/HUnutrition/nearme.html
{% extends 'HUnutrition/base-dashboard.html' %}

{% block dashboard-content %}

<style type="text/css">
	#nearme{
		background-color: rgb(204, 204, 255);
	}
</style>

<div class="row beside-side-nav">
	<div class="row">
		<div class="card-panel">
			<p id="demo">You are in </p> 
		</div>

		<div class="card-panel">
			<ul>
			{% for items in results %}
				<li>{{items.name}} in {{items.vicinity}}</li>
			{% endfor %}
			</ul> 
		</div>
	</div>
</div>

<script>
var x = document.getElementById("demo");

(function getLocation(){
	if (navigator.geolocation)
	{
		navigator.geolocation.getCurrentPosition(showPosition);
	}
	else
	{
		x.innerHTML = "Geolocation is not supported by you browser";
	}
})();

function showPosition(position){
	x.innerHTML = "Latitude: " + position.coords.latitude + "<br>Longitude: " + position.coords.longitude; 
}
</script>

{% endblock %}